### ISSUE TITLE
Implement elastic search or similar

### ISSUE THREAD

**Issue by vincerubinetti** [greenelab/connectivity-search-backend#52]
I believe we're currently using simple substring matching for our node search. Throughout my testing of the frontend, I've come across many cases where I've had to type much more of a gene/compound/disease/etc than I would expect (compared to something like Google) to get it to show up near the top of the list.

Here is one example I found just now, though it's certainly not the best example of the issue:
![image](https://user-images.githubusercontent.com/8326331/57781485-44d09c80-76f8-11e9-8e6a-c1d6b4fd4f6e.png)
In this example, I'd expect epilepsy to come before nicotine dependence. There are other examples (that I can't remember right now) where the thing I'm actually searching for is far far down the list and not visible. The criteria of how to rank results might be difficult to decide on, but I think we could come up with something that performs better than substring matching.

I'd put this feature request near the top of the list of things that would enhance the user experience of using this app, along with #49

**Comment by dongbohu** [comment]
PostgreSQL has some built-in full-text search functionalities. I have been playing with them lately. Try the following search:
http://18.210.24.231/v1/nodes/?search=ep
The search is still based on substring matching, but the results are ranked based on trigram similarity. You can compare the results with the original search:
http://search-api.het.io/v1/nodes/?search=ep

For more information on trigram search, see:
https://www.postgresql.org/docs/11/pgtrgm.html

I also created a new `trgm` parameter that does fuzzy search (allows typo in the search term):
http://18.210.24.231/v1/nodes/?trgm=epilepcy
(Note that http://search-api.het.io/v1/nodes/?search=epilepcy doesn't return anything due to the typo.)
The fuzzy search is based on an absolute similarity threshold, so the shorter the term is, the less matches you may have, This might be counter-intuitive to many users. For example,
http://18.210.24.231/v1/nodes/?trgm=ep
only returns 14 results, while the substring matching (http://search-api.het.io/v1/nodes/?search=ep) returns 2,981 results.

**Comment by dhimmel** [comment]
> The fuzzy search is based on an absolute similarity threshold, so the shorter the term is, the less matches you may have, This might be counter-intuitive to many users.

Is it possible to have a mode that does both search and trigram, such that you get any node matched by either approach?

**Comment by dongbohu** [comment]
@dhimmel, Yes it is possible. The code may not be as lovely. Let me try it.

**Comment by dongbohu** [comment]
@dhimmel and @vincerubinetti, here is a new search API on a test server:
http://18.210.24.231/v1/nodes/?search=ep
It returns the exact substring match of `name` field sorted by trigram similarity values.

To enable fuzzy search, add `fuzzy` option in the URL:
http://18.210.24.231/v1/nodes/?search=ep&fuzzy
The results is a union of exact substring match and fuzzy search (trigram similarity) on `name` field. Again results are sorted by trigram similarity values.

Because of the fuzzy search,  
http://18.210.24.231/v1/nodes/?search=epilepcy&fuzzy 
returns one result in spite of the typo, but 
http://18.210.24.231/v1/nodes/?search=epilepcy 
returns nothing.

**Comment by vincerubinetti** [comment]
Cool. Can I take some time to test it and we can merge it maybe tomorrow? Also if `fuzzy` works as expected, I'd probably always just include it. Don't know if that'd make you want to just have it on by default in the backend, or if Daniel thinks it's useful for people using the endpoints "manually" (without the frontend) to still have the option.

**Comment by dongbohu** [comment]
@vincerubinetti: Take your time. I will keep the test server running until this issue is fixed. 

I am open about whether the fuzzy search should be the default behavior. If you guys prefer, we can even use a brand new parameter name such as `fuzzy-search` to distinguish it from `search`, which does exact matching.

**Comment by vincerubinetti** [comment]
This already works way better than the old way already.

Is there any way to combine the two methods in a way such that this would return Epilepsy first, since I've typed an exact match of the first 3 characters:
![image](https://user-images.githubusercontent.com/8326331/58733878-d829f300-83c3-11e9-8943-cdb373173109.png)

**Comment by dongbohu** [comment]
@vincerubinetti: I tweaked the sorting order so that exact matches are always before non-exact matches. Matches that have same trigram similarity will be sorted alphabetically. So in the following search: 
http://18.210.24.231/v1/nodes/?search=epi&fuzzy
`EPO` and `EPX` are at the end, and `EPO` is before `EPX` because of the alphabetical order.

**Comment by vincerubinetti** [comment]
@dongbohu This looks great from my local testing. ~If you want me to push a test build to my website, I'll need an `https` version of the above test endpoint.~

Actually, just go to https://www.vincentrubinetti.com/hetmech/ and in Chrome click the shield icon to allow "unsafe scripts" so you can see the test server in action:

![image](https://user-images.githubusercontent.com/8326331/58825173-d3578000-860b-11e9-9418-b7021088d28f.png)

**Comment by dongbohu** [comment]
@vincerubinetti: Thanks. I will clean up the backend code and submit a PR.

**Comment by dongbohu** [comment]
Fixed in #59.
