### ISSUE TITLE
Refactor endpoint names/urls

### ISSUE THREAD

**Issue by vincerubinetti** [greenelab/connectivity-search-backend#67]
While coding the frontend, I often get mixed up about which query does which thing; mainly for the node search queries.

Here's how it is now:
```
// lookup specific node by id
https://search-api.het.io/v1/nodes/[NODE_ID]

// search node based on search string
https://search-api.het.io/v1/nodes/?search=[SEARCH]

// search node based on search string, with other node specified so we can sort by # of metapaths to other node
https://search-api.het.io/v1/nodes/?search=[SEARCH_STRING]&count-metapaths-to=[NODE_ID]

// return a list of all nodes connected to specified node, sorted by # of metapaths
https://search-api.het.io/v1/count-metapaths-to/[NODE_ID]

// get random node pair
https://search-api.het.io/v1/random-node-pair/

// search metapaths
https://search-api.het.io/v1/query-metapaths/

// search paths
https://search-api.het.io/v1/query-paths/
```

I propose we change it to this:
```
https://search-api.het.io/v1/nodes/[NODE_ID]
https://search-api.het.io/v1/nodes/?search=[SEARCH_STRING]
https://search-api.het.io/v1/nodes/?search=[SEARCH_STRING]&other-node=[OTHER_NODE_ID]
https://search-api.het.io/v1/nodes/?other-node=[OTHER_NODE_ID]
https://search-api.het.io/v1/nodes/random-pair
https://search-api.het.io/v1/metapaths/
https://search-api.het.io/v1/paths/
```

I think this would be a more clear organization to the queries. Couple of things: 
1) putting all the node related queries under `node`
2) making the "count-metapaths-to" based on parameters rather than different query urls. i think this is closer to what is actually going on
3) the `metatype` filter parameter can then be added to everything under `nodes/`, consistently
4) removing the word "query" from `metapaths` and `paths` (I think this is redundant because all of our endpoints are some kind of query to the backend.

Let's talk about this in person tomorrow.

**Comment by dhimmel** [comment]
@vincerubinetti good point that the following queries all return a list of nodes:

https://search-api.het.io/v1/nodes/?search=%22flash%22
https://search-api.het.io/v1/nodes/?search=%22flash%22&count-metapaths-to=2
https://search-api.het.io/v1/count-metapaths-to/2/

I agree we could simplify the API by getting rid of the `count-metapaths-to` endpoint. Let me look into what that will take in terms of backend changes.

`https://search-api.het.io/v1/nodes/random-pair` doesn't make sense to me because https://search-api.het.io/v1/random-node-pair/ returns a different format.

In the same sense, I actually think https://search-api.het.io/v1/nodes/2/ should be changed to `https://search-api.het.io/v1/node/2/` since it returns a single node rather than an array.

> removing the word "query" from metapaths and paths

I agree with this change.

**Comment by dhimmel** [comment]
Another question is whether we should change `https://search-api.het.io/v1/paths/` to `https://search-api.het.io/v1/paths/<source_id>/<target_id>`.

[This guidance](https://stackoverflow.com/a/4028874/4651668) would advocate the later:

> If you want to return a 404 error when the parameter value does not correspond to an existing resource then I would tend towards a path segment parameter

There are several options for this syntax:

1. `https://search-api.het.io/v1/paths/<source_id>/<target_id>`
2. `https://search-api.het.io/v1/paths/source=<source_id>/target=<target_id>`
3. `https://search-api.het.io/v1/paths/source/<source_id>/target/<target_id>`

@vincerubinetti do you have a perference?

**Comment by vincerubinetti** [comment]
1)

I'd say the other two are too verbose and don't add all that much. I'm thinking if someone is querying for paths, they already know that they need a source and target as input?

**Comment by dhimmel** [comment]
Option 3 seems to be used by tutorials like [this one](https://idratherbewriting.com/learnapidoc/docapis_doc_parameters.html#path_parameters). `paths/source/2/target/4` is longer to type, but a lot more clear from the URL than `paths/2/4`. Will keep working on #68 and we can decide at the end.

**Comment by vincerubinetti** [comment]
If there's clear precedence, then definitely go with that.

**Comment by dhimmel** [comment]
Currently https://github.com/greenelab/hetmech-backend/pull/68 modifies the API to contain the following endpoints:

    "http://localhost:8000/v1/node/2",
    "http://localhost:8000/v1/nodes/",
    "http://localhost:8000/v1/nodes/count-metapaths-to/2/",
    "http://localhost:8000/v1/random-node-pair/",
    "http://localhost:8000/v1/metapaths/source/17054/target/6602/",
    "http://localhost:8000/v1/paths/source/17054/target/6602/metapath/CbGeAlD/"

I now remember why we can't consolidate `/nodes` and `/nodes/count-metapaths-to/2/`. The later sorts results by `metapath_count`, which is a field that does not exist in the database. Since it has to be computed on the fly, it's incompatible with queries whose order is determined by the database, prior to loading into Python.

At least the new design nests the query under `nodes`.

**Comment by dhimmel** [comment]
Now #68 provides the following:

    "http://localhost:8000/v1/node/2",
    "http://localhost:8000/v1/nodes/",
    "http://localhost:8000/v1/random-node-pair/",
    "http://localhost:8000/v1/metapaths/source/17054/target/6602/",
    "http://localhost:8000/v1/metapaths/random-nodes/",
    "http://localhost:8000/v1/paths/source/17054/target/6602/metapath/CbGeAlD/"

https://github.com/greenelab/hetmech-frontend/pull/153 updates the frontend to work with the new endpoints. Will merge them in unison, closing this issue.
